/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package inheritance;

public class Library {
    public boolean someLibraryMethod() {

        return true;
    }

    // Restaurant class
    public static class Restaurant {
       static String name;
       int numberStars;
       int priceCategory;

       // Restaurant constructor
        public Restaurant(String name, int numberStars, int priceCategory) {
            this.name = name;
            this.numberStars = numberStars;
            this.priceCategory = priceCategory;
        }

        // add reviews
        public void addReview(Restaurant name, String body, String author, int numberStars) {
            Review newReview = new Review(name, body, author, numberStars);

            newReview.name.equals(Restaurant.name);

            }
        }

    public static class Review {
        Restaurant name;
        String body;
        String author;
        int numberStars;

        // constructor
        public Review(Restaurant name, String body, String author, int numberStars) {
            this.name = name;
            this.body = body;
            this.author = author;
            this.numberStars = numberStars;

        }

         // string method for reviews
        public String toString() {
            return "Restaurant: " + Restaurant.name + ". " + this.body + " " + "Review by " + this.author + ", " + numberStars + " stars out of 5.";
        }
    }



}
