/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linter;

import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.util.Scanner;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        readJavascriptFile();
    }

    // scanning came from https://docs.oracle.com/javase/tutorial/essential/io/scanning.html
    public static void readJavascriptFile() {
        Scanner s = null;
        int lineCount = 0;
            s = new Scanner(new BufferedReader(new FileReader("./src/main/resources/gates.js")));
            while ((CurrentLine = ReadFile.readLine()) != null); {
                lineCount++;
                if(CurrentLine.trim.endWith(";")){
                                }
                else{
                    System.out.println("Line " + lineCount + " missing semi-colon");
                }


    }
}
}