/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basicLibrary;

import org.junit.Test;

import static basicLibrary.Library.*;
import static org.junit.Assert.*;

public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        Library classUnderTest = new Library();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }

    @Test
    public void testRoll_buildArray(){
        assertTrue("Six sided die is rolled, array values must be added", Library.roll(13).length == 13);
    }



    @Test
    public void testContainsDuplicates_contains() {
        assertTrue("Array should have no duplicates, should return true", Library.containsDuplicates(new int[] {1,2,2,3}));
    }
    @Test
    public void testContainsDuplicates_doesNotContain() {
        assertFalse("Array should have no duplicates, should return false", Library.containsDuplicates(new int[] {1,2,3,4}));
    }

    @Test
    public void testGetLowestAverage() {
        assertArrayEquals("Should find lowest average for nested arrays", new int[]{1,2,3,4}, Library.getLowestAverage(new int[][]{{1,2,3,4}, {5,6,7,8}}));
    }
}
