/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package inheritance;

import org.junit.Before;
import org.junit.Test;
import static org.junit.Assert.*;

public class LibraryTest {
    @Test
    public void testSomeLibraryMethod() {
        Library classUnderTest = new Library();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
    Library.Restaurant testRestaurant;
    @Before
//    @Test
    public void testRestaurant_constructor() {
        testRestaurant = new Library.Restaurant("The Alchemist's Alembic", 5, 3);

    }
    @Test
    public void testRestaurant_toString() {
        assertEquals("String should match Restaurant test", "Name: The Alchemist's Alembic, 5 Stars and 3$ (of $$$$$)", testRestaurant.toString());
    }

    Library.Review testReview;
    @Before
    public void testReview_constructor() {
        testReview = new Library.Review("This place is the best for drinking elven wine.", "Juniper Meadows", 5);
    }

    @Test
    public void testReview_toString() {
        assertEquals("String should match Review test", "Restaurant: The Alchemist's Alembic. The This place is the best for drinking elven wine. Review by Juniper Meadows, 5 stars out of 5.", testReview.toString());
    }



}
